### PR TITLE
Revised adapt-cheat

### PR DESCRIPTION
**Pull request by chris-steele**
I've been working on this revision for a few weeks now, testing in a couple of live projects with QA (e.g. Barclays Principles ken15214) and the vanilla Adapt v2 build (see "Adapt cheat v2 test" here: https://clients.kineo.com/adapt/course/view.php?id=5).

### CODE REVIEW

**Comment by moloko** [comment]
right, I've just been giving this a try on ken15165. first off, there's some great new features here - thanks!

first thing I spotted was that in FF, the cog icon itself is not clickable, instead there seems to be a hit area above and below it... similarly in IE9, whilst the cog icon is clickable there are distinct hit areas above and below it too

the other issue I spotted was that 'pass' and 'fail' didn't seem to be triggering an attempt for any question bar the first - so if I chose pass for example, questions 2 through 4 would have the correct answer selected (and marked) but the reset button would be active and the trickle button wouldn't have appeared. shift-clicking submit (genius idea!) worked fine, however.

**Comment by moloko** [comment]
would it be possible to CTRL+SHIFT+submit to answer a question incorrectly?

**Comment by chris-steele** [comment]
I like that idea, yes, I should think ctrl+shift would work just fine for incorrect answers. I'll get on to that.

The issue with only the first question being answered is because an old version of trickle is being used. I had this prob with another course. All it needs is the update that added the kill event (https://github.com/adaptlearning/adapt-contrib-trickle/commit/3657a8de043a294ea36a0ee3c927e78a03c315db)

Btw the cog seemed fine for me in FF, I'll take a look, though I may have to defer to a more capable FED-type person.

**Comment by chris-steele** [comment]
Actually might not be that simple w.r.t. trickle kill event. I'll have another look!

**Comment by chris-steele** [comment]
OK a full update of trickle will sort it out. According to the log no customisations have been made for ken15165 so this should be safe.

**Comment by moloko** [comment]
karma.conf.js can be deleted

**Comment by moloko** [comment]
OK, can confirm that updating trickle fixes the issue with the reset button appearing

Cog icon still behaving same way for me but I don't think this anything to worry about

**Comment by chris-steele** [comment]
N.B. replicated the cog icon issue - with dev tools open (or just a narrow browser window) the Compass logo rides over it. Like you say nothing to worry about really.

**Comment by moloko** [comment]
If you're done with this I think you should just go ahead and merge - just tag/release the existing version first so we can get back to it easily if we need

**Comment by moloko** [comment]
suggestion for future enhancement - an 'unbank' option for assessments. frequently the QA team need to be able to see all the questions so that they can do a proper content review, so having an option to do this would make this very easy for them.

**Comment by chris-steele** [comment]
Sure thing, thanks Matt. I'll give Ollie a quick shout to get his blessing.

**Pull request merged**
