### PR TITLE
Fix AT config issue

### PR DESCRIPTION
**Pull request by taylortom**

### CODE REVIEW

**Comment by moloko** [comment]
I see what you're doing here but don't understand why it's necessary? If contrib-spoor can add stuff to config.json without it going in `_extensions`, why can't this?

**Comment by taylortom** [comment]
I think spoor's broken

**Comment by moloko** [comment]
eh?

**Comment by taylortom** [comment]
Will keep conversation on here :grin: 

Basically, [this](https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/js/adapt-contrib-spoor.js#L35-L43) won't ever fire if built using the AT

**Comment by moloko** [comment]
surely someone would have spotted that by now...!

**Comment by taylortom** [comment]
Just uploaded [this test](https://clients.kineo.com/qa/mod/scorm/view.php?id=21757)

**Comment by moloko** [comment]
not required, was a bug in the AT that should now be fixed

**Pull request closed without merging**
